import {createClub,getClub,getClubAdministration,getCurrentRole,inviteAdminAction,listClubs} from "../data.js";
import {canResendInvitation,invitationDisplayStatus,invitationLabel,membershipAction,publicClubTournaments} from "../club-administration.js";
const el=id=>document.getElementById(id);let activeAdminClubs=[];let invitationPending=false;

function openClubDialog(onCreated){const dialog=el("club-dialog"),form=el("club-form");form.reset();el("club-active-input").checked=true;el("club-form-feedback").textContent="";el("club-cancel").onclick=()=>dialog.close();form.onsubmit=async event=>{event.preventDefault();const submit=form.querySelector('[type="submit"]');submit.disabled=true;try{const club=await createClub({name:el("club-name-input").value,city:el("club-city-input").value,description:el("club-description-input").value,publicEmail:el("club-email-input").value,publicPhone:el("club-phone-input").value,websiteUrl:el("club-website-input").value,logoUrl:el("club-logo-input").value,active:el("club-active-input").checked});dialog.close();await onCreated?.(club)}catch(error){el("club-form-feedback").textContent=error.message}finally{submit.disabled=false}};dialog.showModal();el("club-name-input").focus()}

function renderClubDirectory(clubs){const list=el("clubs-list");list.replaceChildren();for(const club of clubs.filter(c=>c.active)){const article=document.createElement("article");article.className="club-card";const heading=document.createElement("h2"),link=document.createElement("a"),details=document.createElement("p");link.href=`#/club/${encodeURIComponent(club.slug)}`;link.textContent=club.name;details.textContent=[club.city,club.description].filter(Boolean).join(" — ");heading.append(link);article.append(heading,details);list.append(article)}}
export async function openClubs(){let clubs=await listClubs();renderClubDirectory(clubs);const create=el("clubs-create");create.hidden=await getCurrentRole().catch(()=>null)!=="super_admin";create.onclick=()=>openClubDialog(async club=>{clubs=await listClubs();renderClubDirectory(clubs);el("clubs-feedback").textContent=`Le club ${club.name} a été créé.`})}
export async function openClub(slug){const club=await getClub(slug);el("club-name").textContent=club?.name||"Club introuvable";el("club-description").textContent=club?.description||"";el("club-contact").textContent=[club?.city,club?.public_email,club?.public_phone].filter(Boolean).join(" · ");const list=el("club-tournaments");list.replaceChildren();for(const tournament of publicClubTournaments(club)){const li=document.createElement("li"),a=document.createElement("a");a.href=`#/tournoi/${tournament.slug||tournament.id}`;a.textContent=tournament.name;li.append(a);list.append(li)}}
export function clubOptionLabel(club){return [club.name,club.city].filter(Boolean).join(" — ")}
function renderEmpty(container,message){const row=document.createElement("p");row.className="admin-empty-state";row.textContent=message;container.append(row)}
function renderAdminSelect(selectedId=""){const select=el("admin-club"),submit=el("admin-invite-submit");select.replaceChildren();const prompt=document.createElement("option");prompt.value="";prompt.textContent=activeAdminClubs.length?"Sélectionner un club":"Aucun club actif disponible";select.append(prompt);for(const club of activeAdminClubs){const option=document.createElement("option");option.value=club.id;option.textContent=clubOptionLabel(club);select.append(option)}select.disabled=activeAdminClubs.length===0;if(activeAdminClubs.some(club=>club.id===selectedId))select.value=selectedId;submit.disabled=invitationPending||activeAdminClubs.length===0;el("admin-create-club").classList.toggle("primary",activeAdminClubs.length===0)}
function addRow(container,primary,meta,actions=[]){const row=document.createElement("article");row.className="admin-list-row";const content=document.createElement("div"),title=document.createElement("strong"),details=document.createElement("small");title.textContent=primary;details.textContent=meta;content.append(title,details);row.append(content);if(actions.length){const controls=document.createElement("div");controls.className="admin-row-actions";for(const [label,handler] of actions){const button=document.createElement("button");button.type="button";button.textContent=label;button.onclick=handler;controls.append(button)}row.append(controls)}container.append(row)}
async function refreshAdministration(selectedId=el("admin-club")?.value||""){await inviteAdminAction("sync");const data=await getClubAdministration();activeAdminClubs=data.clubs.filter(c=>c.active===true);renderAdminSelect(selectedId);
  const invitations=el("admin-invitations");invitations.replaceChildren();if(!data.invitations.length)renderEmpty(invitations,"Aucune invitation.");for(const invitation of data.invitations){const actions=canResendInvitation(invitation)?[["Renvoyer",async()=>{await inviteAdminAction("resend",{invitation_id:invitation.id});await refreshAdministration()}],["Révoquer",async()=>{await inviteAdminAction("revoke",{invitation_id:invitation.id});await refreshAdministration()}]]:[];const sent=new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(invitation.created_at));addRow(invitations,invitation.email,`${invitation.clubs?.name||"Club inconnu"} · ${invitationLabel(invitationDisplayStatus(invitation))} · Envoyée le ${sent}`,actions)}
  const members=el("club-admins");members.replaceChildren();if(!data.memberships.length)renderEmpty(members,"Aucun administrateur rattaché.");for(const member of data.memberships)addRow(members,member.profiles?.display_name||member.user_id,`${member.clubs?.name||"Club inconnu"} · ${member.active?"Administrateur actif":"Administrateur désactivé"}`,[[membershipAction(member),async()=>{await inviteAdminAction(member.active?"disable":"reactivate",{club_id:member.club_id,user_id:member.user_id});await refreshAdministration()}]])}
export async function openUserAdministration(){if(await getCurrentRole()!=="super_admin")return false;const feedback=el("admin-feedback");el("admin-create-club").onclick=()=>openClubDialog(async club=>{try{await refreshAdministration(club.active?club.id:"");feedback.textContent=club.active?"Club créé et sélectionné":"Club créé, mais il est inactif et ne peut pas être sélectionné."}catch(error){feedback.textContent=error.message}});el("admin-invite-form").onsubmit=async event=>{event.preventDefault();if(invitationPending)return;const clubId=el("admin-club").value,club=activeAdminClubs.find(item=>item.id===clubId);if(!club){feedback.textContent="Sélectionnez un club actif.";return}invitationPending=true;renderAdminSelect(clubId);try{await inviteAdminAction("invite",{email:el("admin-email").value,club_id:club.id});feedback.textContent="Invitation envoyée.";await refreshAdministration(club.id)}catch(error){feedback.textContent=error.message}finally{invitationPending=false;renderAdminSelect(club.id)}};try{await refreshAdministration()}catch(error){activeAdminClubs=[];renderAdminSelect();feedback.textContent=`Impossible de charger les clubs actifs. ${error.message}`};if(!activeAdminClubs.length&&!feedback.textContent)feedback.textContent="Aucun club actif n’est disponible. Créez un club pour envoyer une invitation.";return true}
