import {createClub,getClub,getClubAdministration,getCurrentRole,inviteAdminAction,listClubs} from "../data.js";
import {canResendInvitation,invitationDisplayStatus,invitationLabel,membershipAction,publicClubTournaments} from "../club-administration.js";
import {createClubCombobox} from "./club-combobox.js";
const el=id=>document.getElementById(id);let adminPicker=null;

function openClubDialog(onCreated){const dialog=el("club-dialog"),form=el("club-form");form.reset();el("club-active-input").checked=true;el("club-form-feedback").textContent="";el("club-cancel").onclick=()=>dialog.close();form.onsubmit=async event=>{event.preventDefault();const submit=form.querySelector('[type="submit"]');submit.disabled=true;try{const club=await createClub({name:el("club-name-input").value,city:el("club-city-input").value,description:el("club-description-input").value,publicEmail:el("club-email-input").value,publicPhone:el("club-phone-input").value,websiteUrl:el("club-website-input").value,logoUrl:el("club-logo-input").value,active:el("club-active-input").checked});dialog.close();await onCreated?.(club)}catch(error){el("club-form-feedback").textContent=error.message}finally{submit.disabled=false}};dialog.showModal();el("club-name-input").focus()}

function renderClubDirectory(clubs){const list=el("clubs-list");list.replaceChildren();for(const club of clubs.filter(c=>c.active)){const article=document.createElement("article");article.className="club-card";const heading=document.createElement("h2"),link=document.createElement("a"),details=document.createElement("p");link.href=`#/club/${encodeURIComponent(club.slug)}`;link.textContent=club.name;details.textContent=[club.city,club.description].filter(Boolean).join(" — ");heading.append(link);article.append(heading,details);list.append(article)}}
export async function openClubs(){let clubs=await listClubs();renderClubDirectory(clubs);const create=el("clubs-create");create.hidden=await getCurrentRole().catch(()=>null)!=="super_admin";create.onclick=()=>openClubDialog(async club=>{clubs=await listClubs();renderClubDirectory(clubs);el("clubs-feedback").textContent=`Le club ${club.name} a été créé.`})}
export async function openClub(slug){const club=await getClub(slug);el("club-name").textContent=club?.name||"Club introuvable";el("club-description").textContent=club?.description||"";el("club-contact").textContent=[club?.city,club?.public_email,club?.public_phone].filter(Boolean).join(" · ");const list=el("club-tournaments");list.replaceChildren();for(const tournament of publicClubTournaments(club)){const li=document.createElement("li"),a=document.createElement("a");a.href=`#/tournoi/${tournament.slug||tournament.id}`;a.textContent=tournament.name;li.append(a);list.append(li)}}
async function refreshAdministration(selectedClub=null){await inviteAdminAction("sync");const data=await getClubAdministration();const active=data.clubs.filter(c=>c.active!==false);if(!adminPicker){adminPicker=createClubCombobox({root:el("admin-club-combobox"),input:el("admin-club"),list:el("admin-club-options"),clubs:active,allowNone:false,allowCreate:true,onCreate:async name=>new Promise(resolve=>openClubDialog(async club=>{await refreshAdministration(club);el("admin-feedback").textContent=`Le club ${club.name} a été créé et sélectionné.`;resolve(club)})),onSelect:()=>{}})}else adminPicker.setClubs(active);if(selectedClub)adminPicker.select(selectedClub);
  const invitations=el("admin-invitations");invitations.replaceChildren();for(const invitation of data.invitations){const li=document.createElement("li");li.textContent=`${invitation.email} — ${invitation.clubs?.name} — ${invitationLabel(invitationDisplayStatus(invitation))} (${invitation.sent_count} envoi(s)) `;if(canResendInvitation(invitation)){for(const [label,action] of [["Renvoyer","resend"],["Révoquer","revoke"]]){const button=document.createElement("button");button.textContent=label;button.onclick=async()=>{await inviteAdminAction(action,{invitation_id:invitation.id});await refreshAdministration()};li.append(button)}}invitations.append(li)}const members=el("club-admins");members.replaceChildren();for(const member of data.memberships){const li=document.createElement("li");li.textContent=`${member.profiles?.display_name||member.user_id} — ${member.clubs?.name} — ${member.role} `;const button=document.createElement("button");button.textContent=membershipAction(member);button.onclick=async()=>{await inviteAdminAction(member.active?"disable":"reactivate",{club_id:member.club_id,user_id:member.user_id});await refreshAdministration()};li.append(button);members.append(li)}}
export async function openUserAdministration(){if(await getCurrentRole()!=="super_admin")return false;el("admin-create-club").onclick=()=>openClubDialog(async club=>{await refreshAdministration(club);el("admin-feedback").textContent=`Le club ${club.name} a été créé et sélectionné. L’e-mail saisi est conservé.`});el("admin-invite-form").onsubmit=async event=>{event.preventDefault();const button=el("admin-invite-submit"),club=adminPicker?.value;button.disabled=true;try{if(!club)throw new Error("Sélectionnez un club actif.");await inviteAdminAction("invite",{email:el("admin-email").value,club_id:club.id});el("admin-feedback").textContent="Invitation envoyée.";await refreshAdministration(club)}catch(error){el("admin-feedback").textContent=error.message}finally{button.disabled=false}};await refreshAdministration();return true}
