import {getCurrentRole,getPlayerProfile,listClubs,listPlayersPage,updatePlayerLocal} from "../data.js";
import {normalizePlayerFilters,playerIdentifier,publicTournaments,ratingLabel} from "../player-directory.js";
function el(id){return document.getElementById(id)}
let filters=normalizePlayerFilters(); let clubs=[];
function setUrl(){const p=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v&&!(k==="page"&&v===1))p.set(k==="clubId"?"club":k,String(v));history.replaceState(null,"",`${location.pathname}${location.search}#/joueurs${p.size?`?${p}`:""}`)}
function activityLabel(value){return value===true?"Actif":value===false?"Inactif":"Non renseignée"}
function renderRows(rows){const body=el("players-directory-body");body.innerHTML="";for(const p of rows){const tr=document.createElement("tr");const link=document.createElement("a");link.href=`#/joueur/${playerIdentifier(p)}`;link.textContent=p.name;const values=[link,p.fide_title||"—",p.fide_id||"—",p.federation||"—",p.clubs?.name||p.club||"—",ratingLabel(p.rating_std),ratingLabel(p.rating_rapid),ratingLabel(p.rating_blitz),activityLabel(p.fide_active)];for(const [i,v] of values.entries()){const td=document.createElement("td");td.dataset.label=["Joueur","Titre","ID FIDE","Fédération","Club","Elo standard","Elo rapide","Elo blitz","Activité"][i];td.append(v instanceof Node?v:document.createTextNode(String(v)));tr.append(td)}body.append(tr)}}
async function load(){el("players-loading").hidden=false;el("players-directory-error").textContent="";try{const result=await listPlayersPage(filters);renderRows(result.players);el("players-count").textContent=`${result.count} joueur(s)`;el("players-prev").disabled=filters.page<=1;el("players-next").disabled=filters.page*result.pageSize>=result.count}catch(e){el("players-directory-error").textContent=e.message}finally{el("players-loading").hidden=true}}
export async function openPlayers(){const q=new URLSearchParams(location.hash.split("?")[1]||"");filters=normalizePlayerFilters({query:q.get("query"),title:q.get("title"),active:q.get("active"),clubId:q.get("club"),rated:q.get("rated"),sort:q.get("sort"),page:q.get("page")});clubs=await listClubs().catch(()=>[]);const club=el("players-club");club.innerHTML='<option value="">Tous les clubs</option>';for(const c of clubs)club.add(new Option(c.name,c.id));for(const [id,key,event] of [["players-search","query","input"],["players-title","title","change"],["players-active","active","change"],["players-club","clubId","change"],["players-rated","rated","change"],["players-sort","sort","change"]]){el(id).value=filters[key];el(id)[`on${event}`]=e=>{filters[key]=e.target.value;filters.page=1;setUrl();load()}}el("players-prev").onclick=()=>{filters.page--;setUrl();load()};el("players-next").onclick=()=>{filters.page++;setUrl();load()};await load()}
export async function openPlayer(identifier){el("player-profile-error").textContent="";const player=await getPlayerProfile(identifier);if(!player){el("player-profile-name").textContent="Joueur introuvable";return}el("player-profile-name").textContent=player.name;el("player-fide-fields").textContent=`Titre ${player.fide_title||"—"} · ID FIDE ${player.fide_id||"—"} · Fédération ${player.federation||"—"} · Période ${player.source_period||"—"} · synchronisé ${player.fide_synced_at?new Date(player.fide_synced_at).toLocaleDateString("fr-CI"):"—"}`;el("player-local-fields").textContent=`Club : ${player.clubs?.name||player.club||"—"}`;el("player-ratings").textContent=`Standard ${ratingLabel(player.rating_std)} · Rapide ${ratingLabel(player.rating_rapid)} · Blitz ${ratingLabel(player.rating_blitz)}`;el("player-activity").textContent=activityLabel(player.fide_active);const list=el("player-tournaments");list.innerHTML="";for(const t of publicTournaments(player)){const a=document.createElement("a");a.href=`#/tournoi/${t.slug||t.id}`;a.textContent=t.name;const li=document.createElement("li");li.append(a);list.append(li)}const role=await getCurrentRole().catch(()=>null);el("player-local-edit").hidden=!['admin','super_admin'].includes(role);el("player-club-edit").value=player.club||"";el("player-local-save").onclick=async()=>{await updatePlayerLocal(player.id,{club:el("player-club-edit").value});el("player-local-feedback").textContent="Champs locaux enregistrés."}}
