import {test,expect} from "@playwright/test";import {readFileSync} from "node:fs";
const mock=readFileSync(new URL("./mock-supabase.js",import.meta.url),"utf8");
test.beforeEach(async({page})=>page.route("https://esm.sh/**",route=>route.fulfill({contentType:"text/javascript",body:mock})));
async function open(page,hash="#/"){await page.goto(`/${hash}`);await expect(page.locator("#startup-error")).toBeHidden()}
async function login(page){await page.locator("#profile-button").click();await page.locator("#login-button").click();await page.locator("#login-email").fill("admin@example.ci");await page.locator("#login-password").fill("secret");await page.locator("#login-form").evaluate(form=>form.requestSubmit());await expect(page.locator("body")).toHaveClass(/is-admin/)}
test("accueil et annuaire",async({page})=>{await open(page);await expect(page.getByRole("heading",{name:/Tournois d’échecs/})).toBeVisible();await page.getByRole("link",{name:"Joueurs"}).click();await expect(page.getByRole("heading",{name:"Annuaire des joueurs"})).toBeVisible()});
test("connexion",async({page})=>{await open(page);await login(page);await expect(page.locator("#auth-name")).toContainText(/Arbitre|admin/)});
test("page tournoi et outils",async({page})=>{await open(page,"#/tournoi/open-abidjan");await expect(page.getByRole("heading",{name:/Open Suisse/})).toBeVisible();await expect(page.getByRole("button",{name:/Liste de départ/})).toBeVisible();await page.evaluate(()=>Object.defineProperty(navigator,"share",{value:undefined,configurable:true}));await page.getByRole("button",{name:"Partager"}).click();await expect(page.getByRole("button",{name:"Lien copié"})).toBeVisible();await page.getByRole("button",{name:"Actualiser"}).click();await expect(page.locator("#realtime-state")).toContainText("connecté")});
test("validation et classement après ronde",async({page})=>{await page.addInitScript(()=>localStorage.setItem("mock-auth","1"));await open(page,"#/tournoi/open-abidjan?onglet=pairings");await page.getByRole("button",{name:"Valider la ronde"}).click();await expect(page.getByText("Classement après la ronde 1")).toBeVisible()});
test("Toutes rondes",async({page})=>{await page.addInitScript(()=>{localStorage.setItem("mock-auth","1");localStorage.setItem("mock-mode","roundrobin")});await open(page,"#/tournoi/open-abidjan?onglet=pairings");await page.getByRole("button",{name:"Valider la ronde"}).click();await expect(page.getByRole("button",{name:/Ronde 2/})).toBeVisible()});
test("Suisse et filtre sans résultat",async({page})=>{await open(page,"#/tournoi/open-abidjan?onglet=pairings");await page.locator("#unplayed-only").check();await expect(page.locator(".pairing-row:not(.pairing-head)")).toHaveCount(0)});
test("création",async({page})=>{await page.addInitScript(()=>localStorage.setItem("mock-auth","1"));await open(page,"#/nouveau-tournoi");await expect(page.getByRole("heading",{name:"Créer un tournoi"})).toBeVisible();await expect(page.getByText("Informations générales",{exact:true})).toBeVisible()});
test("publication",async({page})=>{await page.addInitScript(()=>{localStorage.setItem("mock-auth","1");localStorage.setItem("mock-mode","draft")});await open(page,"#/tournoi/open-abidjan");await page.getByRole("button",{name:"Publier"}).click();await expect(page.locator("#tournament-actions-feedback")).toContainText(/publié/i)});
test("clôture",async({page})=>{await page.addInitScript(()=>localStorage.setItem("mock-auth","1"));await open(page,"#/tournoi/open-abidjan?onglet=pairings");await page.getByRole("button",{name:"Valider la ronde"}).click();page.once("dialog",dialog=>dialog.accept());await page.getByRole("button",{name:/Clôturer/}).click();await expect(page.locator("#rounds-feedback")).toContainText("clôturé")});
test("mobile",async({page},info)=>{test.skip(info.project.name!=="mobile");await open(page,"#/tournoi/open-abidjan");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()});
test("WebKit iPad",async({page},info)=>{test.skip(info.project.name!=="ipad-webkit");await open(page,"#/tournoi/open-abidjan");await expect(page.locator("#tournament-tabs")).toBeVisible()});
test("erreur réseau explicite",async({page})=>{await page.addInitScript(()=>localStorage.setItem("mock-mode","network"));await page.goto("/#/");await expect(page.locator("#home-error")).toContainText(/Impossible de charger/)});
test("navigation clavier et libellés accessibles",async({page})=>{await open(page,"#/tournoi/open-abidjan");await expect(page.locator("main")).toBeVisible();await expect(page.locator('[role="status"]')).toHaveCount(1);await page.keyboard.press("Tab");await expect(page.locator(":focus")).toBeVisible()});
test("budget de ressources statiques",async({page})=>{await open(page,"#/tournoi/open-abidjan");const resources=await page.evaluate(()=>performance.getEntriesByType("resource").filter(entry=>new URL(entry.name).origin===location.origin).length);expect(resources).toBeLessThan(45)});
test("actions d'accueil selon le rôle",async({page})=>{await open(page);await expect(page.locator("#home-actions")).toBeHidden();await page.evaluate(()=>{localStorage.setItem("mock-auth","1");localStorage.setItem("mock-role","admin")});await page.reload();await expect(page.getByRole("link",{name:"Créer un tournoi"})).toBeVisible();await expect(page.getByRole("link",{name:"Utilisateurs"})).toHaveCount(0);await page.evaluate(()=>localStorage.setItem("mock-role","super_admin"));await page.reload();await expect(page.getByRole("link",{name:"Utilisateurs"})).toBeVisible();await expect(page.getByRole("link",{name:"Corbeille"})).toBeVisible()});
test("classement avec départages dans l'ordre",async({page})=>{await page.addInitScript(()=>localStorage.setItem("mock-mode","validated"));await open(page,"#/tournoi/open-abidjan?onglet=standings");const headings=await page.locator("#tournament-standings-table th").allTextContents();expect(headings).toEqual(["#","Joueur","Points","Buchholz","Victoires"]);await expect(page.locator("#tournament-standings-table tbody tr").first().locator("td")).toHaveCount(5)});
test("bannière compacte et page sans débordement",async({page})=>{for(const width of [390,768,1024,1440]){await page.setViewportSize({width,height:900});await open(page);const layout=await page.evaluate(()=>{const hero=document.querySelector(".home-heading"),subtitle=hero.querySelector("p"),actions=document.querySelector("#home-actions");return{heroHeight:hero.getBoundingClientRect().height,subtitleVisible:subtitle.getBoundingClientRect().bottom<=hero.getBoundingClientRect().bottom,actionsBelow:actions.hidden||actions.getBoundingClientRect().top>=hero.getBoundingClientRect().bottom,overflow:document.documentElement.scrollWidth>innerWidth}});expect(layout.subtitleVisible).toBeTruthy();expect(layout.actionsBelow).toBeTruthy();expect(layout.overflow).toBeFalsy();expect(layout.heroHeight).toBeLessThan(width>=1024?290:260)}});
test("aucune inscription publique",async({page})=>{await open(page,"#/tournoi/open-abidjan?onglet=overview");await expect(page.getByRole("link",{name:/S’inscrire/i})).toHaveCount(0);await expect(page.getByRole("button",{name:/Créer un compte/i})).toHaveCount(0);await page.locator("#profile-button").click();await expect(page.locator("#login-button")).toHaveText("Connexion organisateur")});
