import {computeStandingsAfterRound} from "./tiebreaks.js";
import {initialRanking} from "./tournament-page.js";

const escapeXml=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const safeName=value=>String(value||"tournoi").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase();
export function excelWorkbook(sheetName,headers,rows){const row=cells=>`<Row>${cells.map(value=>`<Cell><Data ss:Type="${typeof value==="number"?"Number":"String"}">${escapeXml(value)}</Data></Cell>`).join("")}</Row>`;return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="${escapeXml(sheetName)}"><Table>${row(headers)}${rows.map(row).join("")}</Table></Worksheet></Workbook>`;}
export function startingListExport(payload){const rows=initialRanking(payload.state.players,payload.tournament.rating_type).map(p=>[p.initialRank,p.name,p.title||"",p.fide_id||"",p.federation||"",p.club||"",p.elo||"Non classé"]);return {filename:`${safeName(payload.tournament.name)}-liste-depart.xls`,mime:"application/vnd.ms-excel",content:excelWorkbook("Liste de départ",["Rang","Joueur","Titre","ID FIDE","Fédération","Club","Elo"],rows)};}
export function pairingsExport(payload,roundNumber=null){const rounds=roundNumber?payload.state.rounds.filter(r=>r.number===roundNumber):payload.state.rounds;const names=new Map(payload.state.players.map(p=>[p.id,p.name]));const rows=rounds.flatMap(round=>round.pairings.map(p=>[round.number,p.board??"",names.get(p.white)||"",p.result||"",p.black?names.get(p.black)||"":"Exempt"]));return {filename:`${safeName(payload.tournament.name)}-appariements.xls`,mime:"application/vnd.ms-excel",content:excelWorkbook("Appariements",["Ronde","Table","Blancs","Résultat","Noirs"],rows)};}
export function standingsExport(payload,roundNumber=null){const validated=payload.state.rounds.filter(r=>r.validated_at);const number=roundNumber??validated.at(-1)?.number;if(!number)throw new Error("Aucun classement validé à exporter.");const rows=computeStandingsAfterRound(payload.state,number,payload.tournament.tiebreaks).map(r=>[r.rank,r.name,r.points]);return {filename:`${safeName(payload.tournament.name)}-classement-ronde-${number}.xls`,mime:"application/vnd.ms-excel",content:excelWorkbook("Classement",["Rang","Joueur","Points"],rows)};}
export function resultSheetsExport(payload,roundNumber=null){const rounds=roundNumber?payload.state.rounds.filter(r=>r.number===roundNumber):payload.state.rounds;const names=new Map(payload.state.players.map(p=>[p.id,p.name]));const sections=rounds.map(round=>`<section><h1>${escapeXml(payload.tournament.name)} — Ronde ${round.number}</h1>${round.pairings.filter(p=>p.black).map(p=>`<div class="sheet"><strong>Table ${p.board??""}</strong><p>${escapeXml(names.get(p.white))} — ${escapeXml(names.get(p.black))}</p><p>Résultat : ☐ 1-0 &nbsp; ☐ ½-½ &nbsp; ☐ 0-1</p><p>Signatures : __________________ / __________________</p></div>`).join("")}</section>`).join("");return {filename:`${safeName(payload.tournament.name)}-feuilles-resultats.html`,mime:"text/html;charset=utf-8",content:`<!doctype html><meta charset="utf-8"><title>Feuilles de résultats</title><style>body{font:16px sans-serif}.sheet{border:1px solid #000;padding:1rem;margin:1rem 0;break-inside:avoid}section{break-after:page}</style>${sections}`};}
export function downloadExport(file,documentRef=document){const blob=new Blob([file.content],{type:file.mime});const link=documentRef.createElement("a");link.href=URL.createObjectURL(blob);link.download=file.filename;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
